name: Build Executable

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x64
          - os: macos-latest
            platform: macos
            arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: ${{ matrix.arch }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install imageio
        pip install -r requirements.txt

    - name: Build Application
      run: |
        python -m nuitka \
          --standalone \
          --enable-plugin=pyqt5 \
          --disable-ccache \
          --include-data-dir=resources=resources \
          --windows-icon-from-ico=resources/icon.ico \
          --disable-console \
          --assume-yes-for-downloads \
          main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Notepad-${{ matrix.platform }}-${{ matrix.arch }}
        path: |
          main.dist/